<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
            [
                'title' => 'The Dark Knight',
                'genre' => 'Action',
                'overview' => 'Ketika ancaman yang dikenal sebagai The Joker mengacaukan Gotham, Batman harus menerima salah satu ujian psikologis dan fisik terbesar untuk melawan ketidakadilan.',
                'poster_url' => 'img/darkknight.jpg',
                'rating' => 8.5,
                'release_date' => '2008',
                'director' => 'Christopher Nolan',
                'duration' => '152 menit',
            ],
            [
                'title' => 'Inception',
                'genre' => 'Sci-Fi',
                'overview' => 'Seorang pencuri yang mencuri rahasia perusahaan melalui penggunaan teknologi berbagi mimpi diberi tugas sebaliknya: menanamkan ide ke dalam pikiran seorang CEO.',
                'poster_url' => 'img/inception.jpg',
                'rating' => 8.4,
                'release_date' => '2010',
                'director' => 'Christopher Nolan',
                'duration' => '148 menit',
            ],
            [
                'title' => 'Interstellar',
                'genre' => 'Sci-Fi',
                'overview' => 'Petualangan sekelompok penjelajah yang menggunakan lubang cacing yang baru ditemukan untuk melampaui batas perjalanan ruang angkasa manusia.',
                'poster_url' => 'img/interstellar.jpg',
                'rating' => 8.4,
                'release_date' => '2014',
                'director' => 'Christopher Nolan',
                'duration' => '169 menit',
            ],
            [
                'title' => 'Spirited Away',
                'genre' => 'Animasi',
                'overview' => 'Selama kepindahan keluarganya ke pinggiran kota, seorang gadis berusia 10 tahun mengembara ke dunia yang diperintah oleh para dewa, penyihir, dan roh.',
                'poster_url' => 'img/spirited_away.jpg',
                'rating' => 8.5,
                'release_date' => '2001',
                'director' => 'Hayao Miyazaki',
                'duration' => '125 menit',
            ],
            [
                'title' => 'The Conjuring',
                'genre' => 'Horror',
                'overview' => 'Penyidik paranormal Ed dan Lorraine Warren bekerja untuk membantu keluarga yang mengalami peristiwa menakutkan di rumah pertanian mereka.',
                'poster_url' => 'img/Conjuring.jpg',
                'rating' => 7.5,
                'release_date' => '2013',
                'director' => 'James Wan',
                'duration' => '112 menit',
            ],
            [
                'title' => 'Parasite',
                'genre' => 'Drama',
                'overview' => 'Seluruh anggota keluarga Kim yang tidak memiliki pekerjaan tetap, perlahan menyusup ke dalam kehidupan keluarga kaya Park.',
                'poster_url' => 'img/parasite.jpg',
                'rating' => 8.5,
                'release_date' => '2019',
                'director' => 'Bong Joon-ho',
                'duration' => '132 menit',
            ],
            [
                'title' => 'Your Name',
                'genre' => 'Animasi',
                'overview' => 'Dua remaja berbagi hubungan aneh melalui mimpi di mana mereka bertukar tubuh satu sama lain.',
                'poster_url' => 'img/yourname.jpg',
                'rating' => 8.4,
                'release_date' => '2016',
                'director' => 'Makoto Shinkai',
                'duration' => '106 menit',
            ],
            [
                'title' => 'Get Out',
                'genre' => 'Horror',
                'overview' => 'Seorang pria Afrika-Amerika mengunjungi keluarga kekasihnya yang berkulit putih dan menemukan sesuatu yang sangat mengejutkan.',
                'poster_url' => 'img/getout.jpg',
                'rating' => 7.7,
                'release_date' => '2017',
                'director' => 'Jordan Peele',
                'duration' => '104 menit',
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'genre' => 'Comedy',
                'overview' => 'Kisah petualangan seorang concierge hotel legendaris dan temannya si pelayan dalam mengungkap misteri pembunuhan.',
                'poster_url' => 'img/thegrandbudapesthotel.jpg',
                'rating' => 8.1,
                'release_date' => '2014',
                'director' => 'Wes Anderson',
                'duration' => '99 menit',
            ],
            [
                'title' => 'A Silent Voice',
                'genre' => 'Animasi',
                'overview' => 'Seorang pemuda yang dulu membully gadis tunarungu di sekolah dasar mencoba menebus kesalahannya.',
                'poster_url' => 'img/silentvoice.jpg',
                'rating' => 8.1,
                'release_date' => '2016',
                'director' => 'Naoko Yamada',
                'duration' => '130 menit',
            ],
            [
                'title' => 'Whiplash',
                'genre' => 'Drama',
                'overview' => 'Seorang drummer muda berbakat masuk ke konservatori musik terbaik di negara ini, di mana ia menjadi sasaran seorang instruktur yang tidak kenal ampun.',
                'poster_url' => 'img/whiplash.jpg',
                'rating' => 8.5,
                'release_date' => '2014',
                'director' => 'Damien Chazelle',
                'duration' => '107 menit',
            ],
            [
                'title' => 'Joker',
                'genre' => 'Drama',
                'overview' => 'Seorang komedian gagal di Gotham City perlahan berubah menjadi penjahat psikopat yang dikenal sebagai Joker.',
                'poster_url' => 'img/joker.jpg',
                'rating' => 8.4,
                'release_date' => '2019',
                'director' => 'Todd Phillips',
                'duration' => '122 menit',
            ],
            [
                'title' => 'Coco',
                'genre' => 'Animasi',
                'overview' => 'Seorang bocah yang bercita-cita menjadi musisi secara tidak sengaja masuk ke dunia orang mati dan bertemu leluhurnya.',
                'poster_url' => 'img/coco.jpg',
                'rating' => 8.4,
                'release_date' => '2017',
                'director' => 'Lee Unkrich',
                'duration' => '105 menit',
            ],
            [
                'title' => 'Knives Out',
                'genre' => 'Comedy',
                'overview' => 'Seorang detektif menyelidiki kematian patriark keluarga kaya yang ditemukan tewas sehari setelah ulang tahunnya.',
                'poster_url' => 'img/knivesout.jpg',
                'rating' => 7.9,
                'release_date' => '2019',
                'director' => 'Rian Johnson',
                'duration' => '130 menit',
            ],
            [
                'title' => 'Us',
                'genre' => 'Horror',
                'overview' => 'Sebuah keluarga diserang oleh salinan misterius mereka sendiri saat sedang berlibur di rumah pantai.',
                'poster_url' => 'img/us.jpg',
                'rating' => 6.8,
                'release_date' => '2019',
                'director' => 'Jordan Peele',
                'duration' => '116 menit',
            ],
            [
                'title' => 'The Shawshank Redemption',
                'genre' => 'Drama',
                'overview' => 'Dua orang narapidana menjalin persahabatan selama bertahun-tahun, menemukan penghiburan dan penebusan melalui tindakan kebaikan biasa.',
                'poster_url' => 'img/shawshank.jpg',
                'rating' => 9.3,
                'release_date' => '1994',
                'director' => 'Frank Darabont',
                'duration' => '142 menit',
            ],
            [
                'title' => 'Everything Everywhere All at Once',
                'genre' => 'Sci-Fi',
                'overview' => 'Seorang wanita paruh baya harus terhubung dengan kehidupan paralel dirinya di semesta lain untuk menyelamatkan dunia.',
                'poster_url' => 'img/eeaao.jpg',
                'rating' => 7.8,
                'release_date' => '2022',
                'director' => 'Daniel Kwan & Daniel Scheinert',
                'duration' => '139 menit',
            ],
            [
                'title' => 'Oppenheimer',
                'genre' => 'Drama',
                'overview' => 'Kisah J. Robert Oppenheimer, fisikawan yang memimpin proyek Manhattan untuk mengembangkan bom atom pertama di dunia.',
                'poster_url' => 'img/oppenheimer.jpg',
                'rating' => 8.9,
                'release_date' => '2023',
                'director' => 'Christopher Nolan',
                'duration' => '180 menit',
            ],
            [
                'title' => 'Dune',
                'genre' => 'Sci-Fi',
                'overview' => 'Seorang pemuda berbakat lahir dengan takdir besar di planet gurun yang menyimpan sumber daya paling berharga di alam semesta.',
                'poster_url' => 'img/dune.jpg',
                'rating' => 8.0,
                'release_date' => '2021',
                'director' => 'Denis Villeneuve',
                'duration' => '155 menit',
            ],
            [
                'title' => 'La La Land',
                'genre' => 'Romance',
                'overview' => 'Seorang aktris dan musisi jazz jatuh cinta di Los Angeles sambil mengejar impian mereka masing-masing.',
                'poster_url' => 'img/lalaland.jpg',
                'rating' => 8.0,
                'release_date' => '2016',
                'director' => 'Damien Chazelle',
                'duration' => '128 menit',
            ],
            [
                'title' => 'Hereditary',
                'genre' => 'Horror',
                'overview' => 'Setelah kematian nenek mereka, keluarga Graham mulai mengungkap rahasia gelap tentang warisan keluarga mereka.',
                'poster_url' => 'img/hereditary.jpg',
                'rating' => 7.3,
                'release_date' => '2018',
                'director' => 'Ari Aster',
                'duration' => '127 menit',
            ],
            [
                'title' => 'The Wolf of Wall Street',
                'genre' => 'Comedy',
                'overview' => 'Kisah nyata Jordan Belfort, seorang broker saham New York yang mendirikan perusahaan yang terlibat dalam korupsi dan penipuan.',
                'poster_url' => 'img/wolfofwallstreet.jpg',
                'rating' => 8.2,
                'release_date' => '2013',
                'director' => 'Martin Scorsese',
                'duration' => '180 menit',
            ],
            [
                'title' => 'Catch Me If You Can',
                'genre' => 'Comedy',
                'overview' => 'Kisah nyata Frank Abagnale Jr. yang berhasil menipu jutaan dolar sambil berpura-pura menjadi pilot, dokter, dan jaksa sebelum usia 21 tahun.',
                'poster_url' => 'img/catchme.jpg',
                'rating' => 8.1,
                'release_date' => '2002',
                'director' => 'Steven Spielberg',
                'duration' => '141 menit',
            ],
            [
                'title' => 'Midsommar',
                'genre' => 'Horror',
                'overview' => 'Sepasang kekasih bersama teman-teman mengunjungi festival musim panas di Swedia yang perlahan berubah menjadi mimpi buruk.',
                'poster_url' => 'img/midsommar.jpg',
                'rating' => 7.1,
                'release_date' => '2019',
                'director' => 'Ari Aster',
                'duration' => '148 menit',
            ],
            [
                'title' => 'Tenet',
                'genre' => 'Sci-Fi',
                'overview' => 'Seorang agen rahasia memanipulasi aliran waktu untuk mencegah Perang Dunia Ketiga.',
                'poster_url' => 'img/tenet.jpg',
                'rating' => 7.3,
                'release_date' => '2020',
                'director' => 'Christopher Nolan',
                'duration' => '150 menit',
            ],
            [
                'title' => 'Avengers Endgame',
                'genre' => 'Action',
                'overview' => 'Para Avengers yang tersisa melakukan perjalanan waktu untuk mengumpulkan kembali Infinity Stones dan membalikkan tindakan Thanos.',
                'poster_url' => 'img/endgame.jpg',
                'rating' => 8.4,
                'release_date' => '2019',
                'director' => 'Anthony & Joe Russo',
                'duration' => '181 menit',
            ],
            [
                'title' => 'Spider-Man No Way Home',
                'genre' => 'Action',
                'overview' => 'Peter Parker meminta Doctor Strange untuk membuat dunia melupakan identitasnya sebagai Spider-Man, namun mantra yang salah membuka multiverse.',
                'poster_url' => 'img/spiderman.jpg',
                'rating' => 8.2,
                'release_date' => '2021',
                'director' => 'Jon Watts',
                'duration' => '148 menit',
            ],
            [
                'title' => 'Weathering With You',
                'genre' => 'Animasi',
                'overview' => 'Seorang remaja yang kabur ke Tokyo bertemu dengan gadis yang memiliki kemampuan menghentikan hujan.',
                'poster_url' => 'img/weathering.jpg',
                'rating' => 7.5,
                'release_date' => '2019',
                'director' => 'Makoto Shinkai',
                'duration' => '112 menit',
            ],
            [
                'title' => 'Doctor Strange',
                'genre' => 'Action',
                'overview' => 'Seorang ahli bedah berbakat mengalami kecelakaan yang menghancurkan karirnya, lalu menemukan dunia sihir dan dimensi alternatif.',
                'poster_url' => 'img/doctorstrange.jpg',
                'rating' => 7.5,
                'release_date' => '2016',
                'director' => 'Scott Derrickson',
                'duration' => '115 menit',
            ],
            [
                'title' => 'Barbarian',
                'genre' => 'Horror',
                'overview' => 'Seorang wanita yang menyewa Airbnb di Detroit menemukan ada tamu lain yang sudah memesan rumah yang sama, dan sesuatu yang jauh lebih gelap tersembunyi di bawahnya.',
                'poster_url' => 'img/barbarian.jpg',
                'rating' => 7.5,
                'release_date' => '2022',
                'director' => 'Zach Cregger',
                'duration' => '102 menit',
            ],
            [
                'title' => 'Past Lives',
                'genre' => 'Romance',
                'overview' => 'Dua teman masa kecil dari Korea yang terpisah selama dua dekade bertemu kembali di New York dan merenungkan pilihan hidup mereka.',
                'poster_url' => 'img/pastlives.jpg',
                'rating' => 7.9,
                'release_date' => '2023',
                'director' => 'Celine Song',
                'duration' => '106 menit',
            ],
            [
                'title' => 'Encanto',
                'genre' => 'Animasi',
                'overview' => 'Keluarga Madrigal yang tinggal di pegunungan Kolombia diberkahi keajaiban, kecuali Mirabel yang merasa dirinya biasa saja.',
                'poster_url' => 'img/encanto.jpg',
                'rating' => 7.2,
                'release_date' => '2021',
                'director' => 'Byron Howard & Jared Bush',
                'duration' => '99 menit',
            ],
            [
                'title' => 'Moana',
                'genre' => 'Animasi',
                'overview' => 'Putri kepala suku Polinesia berlayar melintasi samudra untuk menyelamatkan pulau dan rakyatnya bersama setengah dewa Maui.',
                'poster_url' => 'img/moana.jpg',
                'rating' => 7.6,
                'release_date' => '2016',
                'director' => 'Ron Clements & John Musker',
                'duration' => '107 menit',
            ],
            [
                'title' => 'Zootopia',
                'genre' => 'Animasi',
                'overview' => 'Kelinci polisi pertama di kota Zootopia bekerja sama dengan rubah penipu untuk memecahkan kasus hilangnya hewan predator.',
                'poster_url' => 'img/zootopia.jpg',
                'rating' => 8.0,
                'release_date' => '2016',
                'director' => 'Byron Howard & Rich Moore',
                'duration' => '108 menit',
            ],
            [
                'title' => 'Frozen',
                'genre' => 'Animasi',
                'overview' => 'Putri Anna melakukan perjalanan epik bersama seorang pria gunung dan rusa kutubnya untuk menemukan saudarinya Elsa yang memiliki kekuatan es.',
                'poster_url' => 'img/frozen.jpeg',
                'rating' => 7.4,
                'release_date' => '2013',
                'director' => 'Chris Buck & Jennifer Lee',
                'duration' => '102 menit',
            ],
            [
                'title' => 'Tangled',
                'genre' => 'Animasi',
                'overview' => 'Rapunzel yang dikurung di menara selama 18 tahun akhirnya kabur bersama seorang pencuri untuk melihat lampu-lampu ajaib yang selalu ia impikan.',
                'poster_url' => 'img/tangled.jpg',
                'rating' => 7.7,
                'release_date' => '2010',
                'director' => 'Nathan Greno & Byron Howard',
                'duration' => '100 menit',
            ],
            [
                'title' => 'Big Hero 6',
                'genre' => 'Animasi',
                'overview' => 'Seorang remaja jenius dan robot kesayangan kakaknya membentuk tim pahlawan untuk melawan penjahat misterius di kota San Fransokyo.',
                'poster_url' => 'img/bighero6.jpg',
                'rating' => 7.8,
                'release_date' => '2014',
                'director' => 'Don Hall & Chris Williams',
                'duration' => '102 menit',
            ],
            [
                'title' => 'Raya and the Last Dragon',
                'genre' => 'Animasi',
                'overview' => 'Seorang pejuang muda mencari naga terakhir untuk menyelamatkan dunianya dari makhluk jahat yang disebut Druun.',
                'poster_url' => 'img/raya.jpeg',
                'rating' => 7.3,
                'release_date' => '2021',
                'director' => 'Don Hall & Carlos López Estrada',
                'duration' => '107 menit',
            ],
            [
                'title' => 'Turning Red',
                'genre' => 'Animasi',
                'overview' => 'Seorang remaja putri berusia 13 tahun berubah menjadi panda merah raksasa setiap kali ia mengalami emosi yang kuat.',
                'poster_url' => 'img/turningred.jpg',
                'rating' => 7.0,
                'release_date' => '2022',
                'director' => 'Domee Shi',
                'duration' => '100 menit',
            ],
            [
                'title' => 'Luca',
                'genre' => 'Animasi',
                'overview' => 'Seorang anak laut monster laut bersahabat dengan teman barunya dan menjelajahi kota Italia yang indah selama musim panas.',
                'poster_url' => 'img/luca.jpg',
                'rating' => 7.4,
                'release_date' => '2021',
                'director' => 'Enrico Casarosa',
                'duration' => '95 menit',
            ],
            [
                'title' => 'Soul',
                'genre' => 'Animasi',
                'overview' => 'Seorang guru musik yang hampir mendapat kesempatan besar tiba-tiba terpisah dari jiwanya dan harus mencari jalan kembali ke dunia.',
                'poster_url' => 'img/soul.jpg',
                'rating' => 8.0,
                'release_date' => '2020',
                'director' => 'Pete Docter',
                'duration' => '100 menit',
            ],
            [
                'title' => 'Shrek',
                'genre' => 'Animasi',
                'overview' => 'Ogre penyendiri bernama Shrek terpaksa menyelamatkan putri dari menara demi mendapatkan kembali rumahnya yang damai.',
                'poster_url' => 'img/shrek.jpg',
                'rating' => 7.9,
                'release_date' => '2001',
                'director' => 'Andrew Adamson & Vicky Jenson',
                'duration' => '90 menit',
            ],
            [
                'title' => 'Kung Fu Panda',
                'genre' => 'Animasi',
                'overview' => 'Seekor panda gemuk penggemar kung fu dipilih sebagai pahlawan takdir untuk melawan musuh berbahaya yang melarikan diri dari penjara.',
                'poster_url' => 'img/kungfupanda.jpg',
                'rating' => 7.6,
                'release_date' => '2008',
                'director' => 'Mark Osborne & John Stevenson',
                'duration' => '92 menit',
            ],
            [
                'title' => 'How to Train Your Dragon',
                'genre' => 'Animasi',
                'overview' => 'Seorang remaja Viking yang lemah bersahabat dengan naga yang terluka dan bersama-sama mengubah pandangan suku mereka tentang naga.',
                'poster_url' => 'img/httyd.jpg',
                'rating' => 8.1,
                'release_date' => '2010',
                'director' => 'Dean DeBlois & Chris Sanders',
                'duration' => '98 menit',
            ],
            [
                'title' => 'Madagascar',
                'genre' => 'Animasi',
                'overview' => 'Empat hewan kebun binatang New York yang manja tiba-tiba terdampar di pulau liar Madagascar dan harus belajar bertahan hidup.',
                'poster_url' => 'img/madagascar.jpg',
                'rating' => 6.9,
                'release_date' => '2005',
                'director' => 'Eric Darnell & Tom McGrath',
                'duration' => '86 menit',
            ],
            [
                'title' => 'The Bad Guys',
                'genre' => 'Animasi',
                'overview' => 'Sekelompok penjahat hewan terkenal mencoba berpura-pura menjadi baik setelah tertangkap, namun satu dari mereka mulai benar-benar berubah.',
                'poster_url' => 'img/thebadguys.jpg',
                'rating' => 7.1,
                'release_date' => '2022',
                'director' => 'Pierre Perifel',
                'duration' => '100 menit',
            ],
            [
                'title' => 'Puss in Boots The Last Wish',
                'genre' => 'Animasi',
                'overview' => 'Puss in Boots menyadari ia telah menghabiskan 8 dari 9 nyawanya dan harus mencari bintang harapan untuk mendapatkan kembali nyawa-nyawanya.',
                'poster_url' => 'img/pussinboots.jpg',
                'rating' => 7.9,
                'release_date' => '2022',
                'director' => 'Joel Crawford',
                'duration' => '102 menit',
            ],
            [
                'title' => 'Elemental',
                'genre' => 'Animasi',
                'overview' => 'Di kota yang dihuni elemen api, air, tanah, dan udara, seorang gadis api bertemu pria air dan menemukan hal yang tak terduga.',
                'poster_url' => 'img/elemental.jpg',
                'rating' => 7.0,
                'release_date' => '2023',
                'director' => 'Peter Sohn',
                'duration' => '101 menit',
            ],
            [
                'title' => 'Wish',
                'genre' => 'Animasi',
                'overview' => 'Seorang gadis muda membuat permohonan kepada bintang dan mendapat jawaban yang mengubah segalanya di kerajaan Rosas.',
                'poster_url' => 'img/wish.jpg',
                'rating' => 6.1,
                'release_date' => '2023',
                'director' => 'Chris Buck & Fawn Veerasunthorn',
                'duration' => '95 menit',
            ],
            [
                'title' => 'Megamind',
                'genre' => 'Animasi',
                'overview' => 'Penjahat super yang selalu kalah akhirnya berhasil mengalahkan pahlawannya, tapi malah bingung harus berbuat apa setelah menang.',
                'poster_url' => 'img/megamind.jpg',
                'rating' => 7.3,
                'release_date' => '2010',
                'director' => 'Tom McGrath',
                'duration' => '96 menit',
            ],
            [
                'title' => 'Over the Hedge',
                'genre' => 'Animasi',
                'overview' => 'Sekelompok hewan hutan terbangun dari hibernasi dan menemukan sebagian besar hutan mereka telah berubah menjadi perumahan suburban.',
                'poster_url' => 'img/overtheedge.jpg',
                'rating' => 6.8,
                'release_date' => '2006',
                'director' => 'Tim Johnson & Karey Kirkpatrick',
                'duration' => '83 menit',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}
